interface bibleDataSet {
  gen: string;
  exo: string;
  lev: string;
  num: string;
  deu: string;
  jos: string;
  jdg: string;
  rut: string;
  "1sa": string;
  "2sa": string;
  "1ki": string;
  "2ki": string;
  "1ch": string;
  "2ch": string;
  ezr: string;
  neh: string;
  est: string;
  job: string;
  psa: string;
  pro: string;
  ecc: string;
  sng: string;
  isa: string;
  jer: string;
  lam: string;
  ezk: string;
  dan: string;
  hos: string;
  jol: string;
  amo: string;
  oba: string;
  jnh: string;
  mic: string;
  nam: string;
  hab: string;
  zep: string;
  hag: string;
  zec: string;
  mal: string;
  mat: string;
  mrk: string;
  luk: string;
  jhn: string;
  act: string;
  rom: string;
  "1co": string;
  "2co": string;
  gal: string;
  eph: string;
  php: string;
  col: string;
  "1th": string;
  "2th": string;
  "1ti": string;
  "2ti": string;
  tit: string;
  phm: string;
  heb: string;
  jas: string;
  "1pe": string;
  "2pe": string;
  "1jn": string;
  "2jn": string;
  "3jn": string;
  jud: string;
  rev: string;
}

export const BIBLE_DATA_SET: bibleDataSet = {
  gen: "창세기",
  exo: "출애굽기",
  lev: "레위기",
  num: "민수기",
  deu: "신명기",
  jos: "여호수아기",
  jdg: "사사기",
  rut: "룻기",
  "1sa": "사무엘기상",
  "2sa": "사무엘기하",
  "1ki": "열왕기상",
  "2ki": "열왕기하",
  "1ch": "역대상",
  "2ch": "역대하",
  ezr: "에스라기",
  neh: "느헤미야기",
  est: "에스더기",
  job: "욥기",
  psa: "시편",
  pro: "잠언",
  ecc: "전도서",
  sng: "아가",
  isa: "이사야서",
  jer: "예레미야서",
  lam: "예레미야 애가",
  ezk: "에스겔서",
  dan: "다니엘서",
  hos: "호세아서",
  jol: "요엘서",
  amo: "아모스서",
  oba: "오바댜서",
  jnh: "요나서",
  mic: "미가서",
  nam: "나훔서",
  hab: "하박국서",
  zep: "스바냐서",
  hag: "학개서",
  zec: "스가랴서",
  mal: "말라기서",
  mat: "마태복음서",
  mrk: "마가복음서",
  luk: "누가복음서",
  jhn: "요한복음서",
  act: "사도행전",
  rom: "로마서",
  "1co": "고린도전서",
  "2co": "고린도후서",
  gal: "갈라디아서",
  eph: "에베소서",
  php: "빌립보서",
  col: "골로새서",
  "1th": "데살로니가전서",
  "2th": "데살로니가후서",
  "1ti": "디모데전서",
  "2ti": "디모데후서",
  tit: "디도서",
  phm: "빌레몬서",
  heb: "히브리서",
  jas: "야고보서",
  "1pe": "베드로전서",
  "2pe": "베드로후서",
  "1jn": "요한1서",
  "2jn": "요한2서",
  "3jn": "요한3서",
  jud: "유다서",
  rev: "요한계시록",
};
