export { default as Account } from "./Account/Account";
export { default as AccountDetail } from "./Account/AccountDetail";
export { default as Application } from "./Application/Application";
export { default as ApplicationDetail } from "./Application/ApplicationDetail";
export { default as Menuel } from "./Menuel/Menuel";
export { default as MenuelDetail } from "./Menuel/MenuelDetail";
export { default as Rules } from "./Rules/Rules";
export { default as RulesDetail } from "./Rules/RulesDetail";
export { default as Documents } from "./Documents";
